services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_SOURCE=postgresql://user:password@db:5432/gochatdb?sslmode=disable
      - JWT_SECRET=adsfjklsladkfjlsadkjfldaskfjlkajsfdjkfldsaksjdfd;sjkl
      - SERVER_ADDRESS=:8080

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gochatdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: